export const styles = {
  appLayout: { display: 'flex', minHeight: '100vh', backgroundColor: '#faf9f6', fontFamily: 'system-ui, -apple-system, sans-serif' },
  sidebar: { width: '260px', backgroundColor: '#fff', borderRight: '1px solid #e5e5e5', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', padding: '24px 16px', position: 'sticky', top: 0, height: '100vh' },
  logoContainer: { display: 'flex', alignItems: 'center', gap: '10px', padding: '0 12px 24px 12px' },
  logoText: { fontSize: '20px', fontWeight: '700', color: '#2b2b2b', letterSpacing: '-0.5px' },
  navMenu: { display: 'flex', flexDirection: 'column', gap: '4px' },
  navItem: { display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 12px', borderRadius: '8px', border: 'none', backgroundColor: 'transparent', color: '#666', fontSize: '14px', fontWeight: '500', cursor: 'pointer', textAlign: 'left', width: '100%', transition: 'all 0.15s ease' },
  navItemActive: { backgroundColor: '#f3ece7', color: '#ba6e51', fontWeight: '600' },
  sidebarFooter: { display: 'flex', flexDirection: 'column', gap: '12px', borderTop: '1px solid #eee', paddingTop: '16px' },
  userProfile: { display: 'flex', alignItems: 'center', gap: '10px', padding: '8px 12px', backgroundColor: '#f8f8f8', borderRadius: '8px' },
  avatar: { width: '32px', height: '32px', borderRadius: '50%', backgroundColor: '#ba6e51', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '600', fontSize: '12px' },
  userInfo: { display: 'flex', flexDirection: 'column', flex: 1, overflow: 'hidden' },
  userName: { fontSize: '13px', fontWeight: '600', color: '#2b2b2b', textOverflow: 'ellipsis', overflow: 'hidden', whiteSpace: 'nowrap' },
  userRole: { fontSize: '11px', color: '#8e8e8e', textOverflow: 'ellipsis', overflow: 'hidden', whiteSpace: 'nowrap' },
  logoutBtn: { border: 'none', background: 'none', color: '#8e8e8e', cursor: 'pointer', padding: '4px' },
  mainContent: { flex: 1, padding: '32px 40px', maxWidth: '1200px', margin: '0 auto', width: '100%' },
  topHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' },
  searchBox: { display: 'flex', alignItems: 'center', gap: '8px', backgroundColor: '#fff', padding: '8px 16px', borderRadius: '20px', border: '1px solid #e5e5e5' },
  searchInput: { border: 'none', outline: 'none', width: '100%', fontSize: '14px' },
  joinCodeBtn: { display: 'flex', alignItems: 'center', gap: '6px', backgroundColor: '#ba6e51', color: '#fff', border: 'none', padding: '8px 14px', borderRadius: '20px', fontWeight: '600', fontSize: '13px', cursor: 'pointer', animation: 'fadeIn 0.2s ease' },
  bellBtn: { width: '36px', height: '36px', borderRadius: '50%', backgroundColor: '#fff', border: '1px solid #e5e5e5', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  pageHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '24px' },
  title: { fontSize: '28px', fontWeight: '700', color: '#2b2b2b', margin: 0 },
  subtitle: { color: '#666', fontSize: '14px', margin: '4px 0 0 0' },
  primaryBtn: { display: 'flex', alignItems: 'center', gap: '8px', backgroundColor: '#ba6e51', color: '#fff', border: 'none', padding: '10px 18px', borderRadius: '8px', fontWeight: '600', fontSize: '14px', cursor: 'pointer' },
  secondaryBtn: { backgroundColor: '#f0f0f0', color: '#333', border: 'none', padding: '10px 18px', borderRadius: '8px', fontWeight: '600', fontSize: '14px', cursor: 'pointer' },
  backBtn: { display: 'flex', alignItems: 'center', gap: '8px', border: 'none', background: 'none', color: '#ba6e51', fontWeight: '600', cursor: 'pointer', fontSize: '14px', padding: 0 },
  dashboardGrid: { display: 'grid', gridTemplateColumns: '1fr 300px', gap: '24px' },
  leftColumn: { display: 'flex', flexDirection: 'column', gap: '24px' },
  rightColumn: { display: 'flex', flexDirection: 'column', gap: '20px' },
  heroCard: { borderRadius: '16px', minHeight: '180px', backgroundSize: 'cover', backgroundPosition: 'center', position: 'relative', overflow: 'hidden', boxShadow: '0 4px 12px rgba(0,0,0,0.05)' },
  heroOverlay: { backgroundColor: 'rgba(0, 0, 0, 0.45)', padding: '24px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', height: '100%', color: '#fff' },
  heroBadge: { backgroundColor: 'rgba(255, 255, 255, 0.25)', backdropFilter: 'blur(4px)', padding: '4px 10px', borderRadius: '12px', fontSize: '11px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.5px', alignSelf: 'flex-start' },
  heroTitle: { fontSize: '24px', fontWeight: '700', margin: '8px 0 0 0' },
  heroFooter: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: '16px' },
  progressContainer: { flex: 1, maxWidth: '240px' },
  daysText: { fontSize: '12px', opacity: 0.9 },
  progressBar: { height: '4px', backgroundColor: 'rgba(255, 255, 255, 0.3)', borderRadius: '2px', marginTop: '6px', overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: '#fff', width: '40%' },
  heroBtn: { backgroundColor: '#fff', color: '#2b2b2b', border: 'none', padding: '8px 16px', borderRadius: '6px', fontWeight: '600', fontSize: '13px', cursor: 'pointer' },
  heroEmptyCard: { border: '2px dashed #e0e0e0', borderRadius: '16px', padding: '32px', textAlign: 'center', backgroundColor: '#fff' },
  tripsSection: { display: 'flex', flexDirection: 'column', gap: '16px' },
  tripsSectionHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  sectionTitle: { fontSize: '18px', fontWeight: '700', color: '#2b2b2b', margin: 0 },
  controlsRow: { display: 'flex', alignItems: 'center', gap: '12px' },
  cardsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '16px' },
  tripCard: { borderRadius: '12px', height: '160px', backgroundSize: 'cover', backgroundPosition: 'center', position: 'relative', overflow: 'hidden' },
  cardOverlay: { backgroundColor: 'rgba(0, 0, 0, 0.4)', padding: '16px', height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'space-between', color: '#fff' },
  cardMoreBtn: { alignSelf: 'flex-end', border: 'none', background: 'none', cursor: 'pointer', padding: 0 },
  cardTitle: { margin: 0, fontSize: '16px', fontWeight: '600' },
  cardDates: { margin: '2px 0 8px 0', fontSize: '11px', opacity: 0.8 },
  cardBadges: { display: 'flex', gap: '6px', flexWrap: 'wrap' },
  tagBadge: { backgroundColor: 'rgba(255, 255, 255, 0.2)', padding: '2px 6px', borderRadius: '4px', fontSize: '10px' },
  infoBadge: { backgroundColor: 'rgba(0, 0, 0, 0.3)', padding: '2px 6px', borderRadius: '4px', fontSize: '10px' },
  sideCard: { backgroundColor: '#fff', borderRadius: '12px', padding: '20px', border: '1px solid #e5e5e5' },
  sideCardTitle: { fontSize: '15px', fontWeight: '700', margin: '0 0 16px 0', color: '#2b2b2b' },
  statsGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' },
  statBox: { backgroundColor: '#faf9f6', padding: '12px', borderRadius: '8px', textAlign: 'center' },
  statNumber: { display: 'block', fontSize: '20px', fontWeight: '700', color: '#ba6e51' },
  statLabel: { fontSize: '11px', color: '#666' },
  emptyTripsBox: { padding: '40px', textAlign: 'center', backgroundColor: '#fff', borderRadius: '12px', border: '1px solid #e5e5e5' },
  emptyTitle: { margin: '12px 0 4px 0', fontSize: '16px' },
  emptyText: { margin: 0, fontSize: '13px', color: '#666' },
  loaderContainer: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '60px' },
  segmentedControl: { display: 'flex', backgroundColor: '#eee', padding: '3px', borderRadius: '8px', gap: '2px' },
  segmentedBtn: { padding: '6px 16px', border: 'none', backgroundColor: 'transparent', borderRadius: '6px', fontSize: '13px', fontWeight: '500', color: '#666', cursor: 'pointer' },
  segmentedBtnActive: { backgroundColor: '#fff', color: '#2b2b2b', fontWeight: '600', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' },
  segmentedControlSmall: { display: 'flex', backgroundColor: '#eee', padding: '2px', borderRadius: '6px', gap: '2px' },
  segmentedBtnSmall: { padding: '4px 10px', border: 'none', backgroundColor: 'transparent', borderRadius: '4px', fontSize: '12px', color: '#666', cursor: 'pointer' },
  segmentedBtnActiveSmall: { backgroundColor: '#fff', color: '#2b2b2b', fontWeight: '600' },
  prepCard: { backgroundColor: '#fff', borderRadius: '8px', border: '1px solid #e5e5e5', overflow: 'hidden' },
  prepCardHeader: { padding: '12px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer' },
  checkboxBtn: { border: 'none', background: 'none', cursor: 'pointer', padding: 0, display: 'flex', alignItems: 'center' },
  prepTitle: { fontSize: '14px', fontWeight: '500' },
  prepDeadline: { fontSize: '12px', color: '#8e8e8e', display: 'flex', alignItems: 'center' },
  expandBtn: { border: 'none', background: 'none', cursor: 'pointer', color: '#8e8e8e', display: 'flex', alignItems: 'center' },
  prepCardBody: { padding: '12px 16px', borderTop: '1px solid #f0f0f0', backgroundColor: '#fafafa', display: 'flex', flexDirection: 'column', gap: '8px' },
  prepDetailRow: { display: 'flex', gap: '8px', alignItems: 'baseline' },
  prepDetailLabel: { fontSize: '12px', fontWeight: '600', color: '#8e8e8e', width: '80px' },
  prepLink: { fontSize: '13px', color: '#ba6e51', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '4px' },
  prepActionsRow: { display: 'flex', gap: '12px', marginTop: '8px', paddingTop: '8px', borderTop: '1px dashed #e0e0e0' },
  prepActionBtn: { border: 'none', background: 'none', fontSize: '12px', color: '#666', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', padding: 0 },
  placeholderContainer: { padding: '60px 20px', textAlign: 'center', backgroundColor: '#fff', borderRadius: '12px', border: '1px solid #e5e5e5' },
  placeholderIconWrapper: { marginBottom: '16px' },
  placeholderTitle: { margin: '0 0 8px 0', fontSize: '20px' },
  placeholderSubtitle: { margin: 0, color: '#8e8e8e', fontSize: '14px' },
  memberRowCard: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 16px', backgroundColor: '#fff', borderRadius: '10px', border: '1px solid #e5e5e5', boxShadow: '0 1px 3px rgba(0,0,0,0.02)' },
  memberAvatar: { width: '36px', height: '36px', borderRadius: '50%', backgroundColor: '#ba6e51', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: '600', fontSize: '13px' },
  roleBadge: { fontSize: '11px', fontWeight: '600', color: '#ba6e51', backgroundColor: '#f3ece7', padding: '2px 8px', borderRadius: '4px', alignSelf: 'flex-start' },
  moreActionsBtn: { border: 'none', background: 'none', cursor: 'pointer', padding: '4px', borderRadius: '4px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 },
  modalContent: { backgroundColor: '#fff', borderRadius: '12px', padding: '24px', width: '100%', maxWidth: '440px', boxShadow: '0 10px 25px rgba(0,0,0,0.1)' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' },
  closeBtn: { border: 'none', background: 'none', cursor: 'pointer', color: '#8e8e8e' },
  modalForm: { display: 'flex', flexDirection: 'column', gap: '14px' },
  label: { display: 'block', fontSize: '12px', fontWeight: '600', color: '#4a4a4a', marginBottom: '4px' },
  input: { width: '100%', padding: '8px 12px', borderRadius: '6px', border: '1px solid #ccc', fontSize: '14px', outline: 'none', boxSizing: 'border-box' },
  modalActions: { display: 'flex', justifyContent: 'flex-end', gap: '8px', marginTop: '8px' },
  errorBanner: { backgroundColor: '#fde8e8', color: '#e53e3e', padding: '8px 12px', borderRadius: '6px', fontSize: '13px' },
  successBanner: { backgroundColor: '#e6fffa', color: '#234e52', padding: '8px 12px', borderRadius: '6px', fontSize: '13px' }
}